#!/usr/bin/env -S awk -f ${_} -- query.go

BEGIN {
    print "//Code generated by Decap (`./spectura_typegen.awk | gofmt`). DO NOT EDIT.\n"
    print "package decap\n"
}

/^type [A-Z]\w+ (\[\])?(byte|int|string)/ {
    printf "%s\n\n", $0
}

/^type [A-Z]\w+ struct/ {
    handle_struct = 1
    print $0
}

/^\t[A-Z]/ && handle_struct {
    print $0
}

/^}/ && handle_struct {
    printf "%s\n\n", $0
    handle_struct = 0
}
